spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://handfarm.co.kr/handfarm?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&amp
    username: farmer
    password: handfarm1!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        web: debug
    sql: debug
